services:
  - type: web
    name: iris-mlflow-server
    runtime: python
    plan: starter

    buildCommand: pip install mlflow psycopg2-binary

    startCommand: >
      mlflow server
      --host 0.0.0.0
      --port $PORT
      --backend-store-uri sqlite:////var/data/mlflow.db
      --artifacts-destination /var/data/artifacts

    disk:
      name: mlflow-data
      mountPath: /var/data
      sizeGB: 10